### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by wackywendell** [substrait-io/substrait-validator#290]
There's been a suite of recent changes to `substrait-validator`, and it would be useful to release a new version, as mentioned briefly [here](https://github.com/substrait-io/substrait-validator/pull/274#pullrequestreview-2355811859).

I'm opening this issue to raise the question - what features or changes (outside [the documented release](https://github.com/substrait-io/substrait-validator/blob/1f351c63fda50754958c635e6b7ca0f210bebfa8/RELEASE.md) chores) do we want before we're ready for a new version?

**Comment by mbrobbel** [comment]
In my opinion we can just bump versions and push a new release now and repeat this whenever beneficial.

**Comment by wackywendell** [comment]
Ah, ok! Fair enough.

🤔  I'm not sure how automated it currently is / how well it will work; it looks like there's a [Github Action](https://github.com/substrait-io/substrait-validator/blob/0b1fbbba0f04752bd593260fb55b3cd599690481/.github/workflows/rust.yml#L109) for releasing ([Python too](https://github.com/substrait-io/substrait-validator/blob/0b1fbbba0f04752bd593260fb55b3cd599690481/.github/workflows/python.yml#L105)), so if we [tag the commit with a version number](https://github.com/substrait-io/substrait-validator/blob/0b1fbbba0f04752bd593260fb55b3cd599690481/.github/workflows/rust.yml#L7) that should trigger it? I guess we'll have to see how functional that is 🤞 

I can put together a PR for that. @mbrobbel - did you want to get #276 in first? It looks like that would update the Python packager `maturin`, which might affect this.

**Comment by mbrobbel** [comment]
> did you want to get #276 in first?

No, let's not block this release on that.

**Comment by wackywendell** [comment]
OK! I'll put together a PR for that. Any thoughts on the version number?

We're currently at 0.0.11; perhaps its time to go to 0.1.0? This seems like more than a patch update, but pre-1.0 I'm not sure it matters much...

**Comment by wackywendell** [comment]
^ OK! I made a PR. I went with 0.1.0 for now, but its real easy to switch if there are other opinions. Thanks for your help on this!
