### ISSUE TITLE
Unexpected and unobvious build failures when git submodules not downloaded

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait-validator#34]
I had not run `git submodule init && git submodule update` (I hadn't realized there were submodules originally).  When I ran the python build I ended up with an error on:

```
    let input_paths = input_paths
        .map(|p| dunce::canonicalize(p).unwrap())
        .collect::<Vec<_>>();
```

I believe it was trying to canonicalize `../substrait/proto` and because `../substrait` existed but `../substrait/proto` did not it ended up getting a "file not found" error.

**Comment by jvanstraten** [comment]
I was sure there were at least build instructions that specify that you need to check out submodules but I can't find any obvious ones. And you're right; I never did bother to make better build error messages so I can imagine they can come off as pretty cryptic. Thanks for the report; will improve when able.
